version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slack-frontend
    ports:
      - "5025:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - slack-network

networks:
  slack-network:
    name: slack-network
    driver: bridge 