version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - DATABASE_URL=mongodb://admin:secret@remoteserver/slack?authSource=admin
    ports:
      - "3000:3000"